exports = module.exports = {
  ProductListName: 'Product',
  ProductTypeListName: 'ProductType',
  AccountListName: 'Account',
  AccountRecordListName: 'AccountRecord',
  PeriodListName: 'Period',
  TransactionListName: 'Transaction',
  FarmerListName: 'Farmer',
  RoleListName: 'Role',
  UserListName: 'User',
  ShopListName: 'Shop',
  PermissionListName: 'Permission',
  RegulatedListName: 'RegulatedList',
  DBRecordListName: 'DBRecord',
  SystemListName: 'System',
  CityListName: 'City',
  AddrPrefixListName: 'AddrPrefix',
	VillageListName: 'Village',
	CustomerSurveyListName: 'CustomerSurvey'
};
